name: API tests

on:
    pull_request:

jobs:
    unittests:
        strategy:
            matrix:
                php-version: [ '7.2', '8.0' ]
        name: curl tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  # test the lowest version, to make sure checks pass on it
                  php-version: ${{ matrix.php-version }}
                  extensions: json, mbstring, pdo, curl, pdo_sqlite
                  coverage: none
            - name: Initialise
              run: |
                  sudo composer self-update -q	
            - name: Install dependencies
              run: |
                  sudo COMPOSER_MEMORY_LIMIT=-1 COMPOSER_PROCESS_TIMEOUT=60 composer update --prefer-dist --no-progress
            - name: Initialise the database
              run: make db-create
            - name: create api user
              run: php bin/console bolt:add-user apiuser apiuser%1 api@example.org API --roles=ROLE_WEBSERVICE
            - name: check authorisation blocks unauthorised
              run: |
                [[ $(curl --write-out "%{http_code}\n" --silent --output /dev/null "https://localhost:8001/api/contents/") == 401 ]] && echo "OK"
            - name: check API user gets content
              run: curl -fkI -u apiuser:apiuser%1 https://localhost:8001/api/contents
            - name: check API user gets fields
              run: curl -fkI -u apiuser:apiuser%1 https://localhost:8001/api/fields
            - name: check API user gets relations
              run: curl -fkI -u apiuser:apiuser%1 https://localhost:8001/api/relations
